### ISSUE TITLE
ptite question

### ISSUE THREAD

**Issue by Curlypla** [Ca-ressemble-a-du-fake/site#1]
Comme j'avais aucun moyen de vous contacter j'ai fait une issue, j'ai vu que vous avez tous essayé pour cloner une voix en Français. Je suis aussi beaucoup ça et je connais les modèles et tt mais je n'ai jamais eu de bon résultat. Avez vous réussi finalement a avoir de bon résultat après tous vos efforts et si oui avec quelle modèle, temps d'entrainement?

**Comment by Ca-ressemble-a-du-fake** [comment]
Bonjour, oui les résultats sont assez bons. Je suis en train de rédiger un tuto là dessus. En attendant, tu peux regarder du côté de l'équipe de coqui tts qui ont repris et amélioré mozilla tts. En quelques jours tu peux avoir des résultats très corrects.
